#!/bin/sh
#  usage: chapter-mark [SLEEP]
set -euf

SLEEP=${1:-0}
CDIR=${CDIR:-$HOME/.local/share/chapter-marker}
MARKER=$CDIR/marker
SHOW=$CDIR/show
CHAPTER_FILE="$CDIR/$(cat "$SHOW")_chapters.txt"

if ! test -e "$MARKER" -o -e "$SHOW";then
  notify-send -u critical "Error" "$MARKER or $SHOW does not exist\nrun chapter-start first"
  exit 1
fi
if ! test -e "$CHAPTER_FILE";then
  notify-send -u critical "Error" "current Chapter file at \n$CHAPTER_FILE does not exist\nrun chapter-start first"
  exit 1
fi

DIFF=$(($(date +%s) - $(cat "$MARKER")))

marker=$(date -u -d "@$DIFF" +%H:%M:%S.%3N)

sleep "$SLEEP"
headline=$(xclip -selection primary -o | tr '\n' ' ' | sed -e 's/^[ ]*//' -e 's/[ ]*$//')
entry="$marker $headline"

# some window managers need a short delay for xdotool to work
# xdotool sleep 0.15 type --clearmodifiers " $marker "

echo "$entry" >> "$CHAPTER_FILE"
notify-send "chaptermark created" "$entry"
