name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.6.1
          python -m poetry install

      - name: run backend linter
        run: |
          python -m poetry run ruff check chapter_marker

      - name: build and install
        run: |
          python -m poetry build
          python -m poetry install

      - name: run chapter-marker
        uses: GabrielBB/xvfb-action@v1
        with:
          run: python -m poetry run chapter-marker --help
